on: push

jobs:
  build-debs:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: jtdor/build-deb-action@v1
        with:
          buildpackage-opts: --build=binary --no-sign
      - uses: actions/upload-artifact@v3
        with:
          name: Artifacts
          path: debian/artifacts
    
