on: push

jobs:
  build-debs:
    strategy:
      matrix:
        os: [ubuntu-22.04, ubuntu-22.04-arm]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: jtdor/build-deb-action@v1
        with:
          artifacts-dir: debian/artifacts-${{ matrix.architecture }}
          buildpackage-opts: --build=binary --no-sign
          docker-image: ubuntu:22.04
      - uses: actions/upload-artifact@v4
        with:
          name: Artifacts-${{ matrix.architecture }}
          path: debian/artifacts-${{ matrix.architecture }}
    
